[package]
name = "sdrill"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
crossterm = "0.23"
rusqlite = "0.27"
structopt = "0.3"
